# Generated by Django 3.1.1 on 2020-09-29 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_marketpost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marketpost',
            old_name='title',
            new_name='type_of_item',
        ),
    ]
