# Generated by Django 3.1.1 on 2020-09-29 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_auto_20200928_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketpost',
            name='image',
            field=models.FileField(upload_to='marketplace/'),
        ),
    ]
