# Generated by Django 3.1.1 on 2020-09-29 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_auto_20200929_0229'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.FileField(default='', upload_to='marketplace/'),
            preserve_default=False,
        ),
    ]
